[build]
command = "npm run build"
functions = "functions"
publish = "build"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/a/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
