[build]
  functions = "netlify/functions"  # Should match Webpack output directory
  publish = "public"

[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
