[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public" # Change this to the directory where your HTML files are located

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
